### ISSUE TITLE
[RFE] require php-cs-fix and use it

### ISSUE THREAD

**Issue by ghost** [gskema/prestashop-installer#10]
Assure a coding consistency using [fabpot/php-cs-fixer](http://cs.sensiolabs.org/)

**Comment by gskema** [comment]
Like in your modules `composer.json` file? Not really familiar with that (the auto fix part), where can I read about it?

**Comment by ghost** [comment]
Yes, I use it in my modules ..  I linked the home page of the project (http://cs.sensiolabs.org/) .. is by SensioLabs so it is assured to be a very good code

Just require it in composer.json .. then add a .php_cs configuration file in your project .. that's all 

``` php
<?php
return Symfony\CS\Config\Config::create()
    ->fixers(array('-psr0'))  // don't check class names
    ->level(Symfony\CS\FixerInterface::PSR2_LEVEL)  // PSR2
    ->setUsingCache(true)  // speed up
    ->finder(
        Symfony\CS\Finder\DefaultFinder::create()
            ->in(__DIR__)  // check everything from the root 
    )
;
```

**Comment by gskema** [comment]
Hmm cool, I'll check it out. Why not make this into a test so you can test PSR-2 while developing? Travis could still run the test.

**Comment by ghost** [comment]
I run it in travis in fact :)

https://github.com/ZiZuu-store/zzCleanURLs/blob/integrate-travis-ci/.travis.yml#L91

**Comment by gskema** [comment]
So do you use it only to check compliance with PSR-2?

**Comment by ghost** [comment]
It checks indentation and a lot of things, plus psr2. It has a lot of config and one can check a wide plethora of things

**Comment by ghost** [comment]
@gskema don't forget it ;)

**Comment by gskema** [comment]
@ZiZuu-store I haven't had the time to check it out. The problems is I don't what good is it going to do me. The code is 100% PSR-2 before it hits the repository, because I see and fix all warnings in the IDE. What is there besides PSR-2? SensioLabs Insights is hooked up and gives the codes tips.
