### ISSUE TITLE
Usage on Windows

### ISSUE THREAD

**Issue by kpodemski** [gskema/prestashop-installer#11]
![image](https://cloud.githubusercontent.com/assets/2137763/13902630/fd7b4666-ee4f-11e5-8090-a5c2ff4d58c2.png)

I assume it is because of dependencies conflict?

**Comment by kpodemski** [comment]
I solved it by running `composer global update symfony/filesystem` but of course it is not a best idea, you write that we should use `bin-dir`, any chances for a quick tip of how done that?

Also, to avoid `self signed certificate` problem with guzzle I've used:
`$this->client->setDefaultOption('verify', false);`

**Comment by gskema** [comment]
This means that you have some other global package installed that uses the same dependencies as this one. Global packages are installed to the same folder and therefore share the same dependencies from `vendor` folder, meaning there are conflicts.

Technically I could get rid of Guzzle and Filesystem, but they're so useful :) . It is possible to avoid these conflict by installing this package somwhere else and just adding the `bin/prestashop` to system PATH.

P.S. can you write more about `self signed certificate` problem?

**Comment by kpodemski** [comment]
To be honest I don't know what more to write about this problem with certificate, guzzle was not able to download PrestaShop for me, I've had to change this param to `false` to prevent this problem... other option was to provide some path to certificate - I don't know if it OS related or it's just me
