### ISSUE TITLE
Guided installation process

### ISSUE THREAD

**Issue by gskema** [gskema/prestashop-installer#3]
- Create a dialog between the user to collect installation data;
- Call `index_cli.php` with the collected data

**Comment by kpodemski** [comment]
:+1: 

I wanted to create issue about it but I see that you think about that, it will be super cool to provide access to database etc. using step-by-step method

**Comment by gskema** [comment]
I though about it and I don't think it would be technically possible to call CLI script from another CLIS script, because PrestaShop expects CLI arguments, which I can't simulate from my already running script. I haven't looked at it yet, maybe it would be possible somehow
