### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by gskema** [gskema/prestashop-installer#8]

**Comment by ghost** [comment]
:+1:

**Comment by gskema** [comment]
Sorry, I'm too lazy :D

**Comment by ghost** [comment]
but your package will be perfect for modules' developers that have to perform consistent PS installations for CI ..

but performing test on my module using a non-tested module is a counter-sense :)

It could be a good requirement for my [travis integration branch](https://github.com/ZiZuu-store/zzCleanURLs/tree/integrate-travis-ci)

**Comment by gskema** [comment]
https://github.com/gskema/prestashop-installer/tree/dev wrote some tests (one :laughing:)

**Comment by ghost** [comment]
:+1:  :)
